name: altogic_flutter
description: Altogic Flutter Client Implementation
homepage:
version: 0.0.2
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  altogic_dart: 0.0.4
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6
  uni_links: ^0.5.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter: